version: '3.8'

services:
  fastadmin:
    build:
      context: .
    container_name: fastadmin-dev
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped

